namespace Quilt.Mac.AppKit {
	public enum NSEventMask : ulong {
		LeftMouseButtonDown = 1ul << (int)NSEventType.LeftMouseDown,
		LeftMouseUp = 1ul << (int)NSEventType.LeftMouseUp,
		RightMouseDown = 1ul << (int)NSEventType.RightMouseDown,
		RightMouseUp = 1ul << (int)NSEventType.RightMouseUp,
		MouseMoved = 1ul << (int)NSEventType.MouseMoved,
		LeftMouseDragged = 1ul << (int)NSEventType.LeftMouseDragged,
		RightMouseDragged = 1ul << (int)NSEventType.RightMouseDragged,
		MouseEntered = 1ul << (int)NSEventType.MouseEntered,
		MouseExited = 1ul << (int)NSEventType.MouseExited,
		KeyDown = 1ul << (int)NSEventType.KeyDown,
		KeyUp = 1ul << (int)NSEventType.KeyUp,
		FlagsChanged = 1ul << (int)NSEventType.FlagsChanged,
		AppKitDefined = 1ul << (int)NSEventType.AppKitDefined,
		SystemDefined = 1ul << (int)NSEventType.SystemDefined,
		ApplicationDefined = 1ul << (int)NSEventType.ApplicationDefined,
		Periodic = 1ul << (int)NSEventType.Periodic,
		CursorUpdate = 1ul << (int)NSEventType.CursorUpdate,
		ScrollWheel = 1ul << (int)NSEventType.ScrollWheel,
		TabletPoint = 1ul << (int)NSEventType.TabletPoint,
		TabletProximity = 1ul << (int)NSEventType.TabletProximity,
		OtherMouseDown = 1ul << (int)NSEventType.OtherMouseDown,
		OtherMouseUp = 1ul << (int)NSEventType.OtherMouseUp,
		OtherMouseDragged = 1ul << (int)NSEventType.OtherMouseDragged,
		EventGesture = 1ul << (int)NSEventType.Gesture,
		EventMagnify = 1ul << (int)NSEventType.Magnify,
		EventSwipe = 1ul << (int)NSEventType.Swipe,
		EventRotate = 1ul << (int)NSEventType.Rotate,
		EventBeginGesture = 1ul << (int)NSEventType.BeginGesture,
		EventEndGesture = 1ul << (int)NSEventType.EndGesture,
		SmartMagnify = 1ul << (int)NSEventType.SmartMagnify,
		Pressure = 1ul << (int)NSEventType.Pressure,
		DirectTouch = 1ul << (int)NSEventType.DirectTouch,
		AnyEvent = unchecked(ulong.MaxValue)
	}
}
